### ISSUE TITLE
ERROR: dependency ‘scrypt’ is not available for package ‘keybase’

### ISSUE THREAD

**Issue by ignacio82** [ropenscilabs/keybase#2]
I'm having troubles installing your package. 
```
> devtools::install_github('hrbrmstr/keybase')
Downloading GitHub repo hrbrmstr/keybase@master
from URL https://api.github.com/repos/hrbrmstr/keybase/zipball/master
Installing keybase
'/usr/local/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL '/tmp/RtmpxbvCxy/devtoolsa72d0ae973/hrbrmstr-keybase-803feb0'  \
  --library='/usr/local/lib/R/site-library' --install-tests 

ERROR: dependency ‘scrypt’ is not available for package ‘keybase’
* removing ‘/usr/local/lib/R/site-library/keybase’
Installation failed: Command failed (1)
```

What am I missing?

**Comment by ignacio82** [comment]
I think the problem is that the package ‘scrypt’ was removed from the CRAN repository.

https://cran.r-project.org/web/packages/scrypt/index.html

**Comment by hrbrmstr** [comment]
ugh. i hadn't seen that. lemme see what i can do. thx for reporting!

**Comment by ignacio82** [comment]
Installing `scrypt` from github solves the issue

```
devtools::install_github('rstudio/rscrypt')
```

I wonder why it was removed from cran.  Will your package be available on cran at some point?

**Comment by hrbrmstr** [comment]
Thx. I'm working on taking over maintenance for `scrypt` from the RStudio folks and I will be shunting `keybase` over to CRAN before the end of H1.
