### ISSUE TITLE
help encrypting a file

### ISSUE THREAD

**Issue by ignacio82** [ropenscilabs/keybase#3]
I was able to install keybase and I can encrypt a file for myself. For example:

```
library(keybase)
secret.df <- data.frame(x=rnorm(100), y=runif(100))
saveRDS(secret.df, "df.RDS")
kb_encrypt_file(users = "ignacio", infile = 'df.RDS', outfile = 'df.encrypted', binary = TRUE)
```

Alas, I cannot figure out how to encrypt a file for someone else:

```
> kb_encrypt_file(users = "hrbrmstr", infile = 'df.RDS', outfile = 'df2.encrypted', binary = TRUE)
Warning message:
running command ''/usr/bin/keybase' encrypt hrbrmstr -b -i 'df.RDS' -o 'df2.encrypted' 2>&1' had status 2 
```

What am I doing wrong?

**Comment by RMHogervorst** [comment]
could it be that you are first encrypting the file for yourself:
`kb_encrypt_file(users = "ignacio", infile = 'df.RDS', outfile = 'df.encrypted', binary = TRUE)`

and than try to encrypt that file for someone else?
`> kb_encrypt_file(users = "hrbrmstr", infile = 'df.RDS', outfile = 'df2.encrypted', binary = TRUE)`
