### ISSUE TITLE
add wrapper around keybase-website specific 'keybase pgp decrypt -m "message"' ?

### ISSUE THREAD

**Issue by RMHogervorst** [ropenscilabs/keybase#4]
Of course you can run kb_cmd(keybase pgp decrypt -m "message") 
but since the keybase website can be a first interaction with encryption is it perhaps useful to also add this function to the keybase wrapper?

If so, I'd be happy to implement it

**Comment by hrbrmstr** [comment]
Superb idea! Have at thee! (and #ty!)

**Comment by RMHogervorst** [comment]
Hi @hrbrmstr ,
Do you have any tips?
The pgp encryption results in multiple lines. 
The decrypt tries to  decrypt every line, which does not work.

**Comment by hrbrmstr** [comment]
will take a look this week (I'm triaging issues & PRs post-vacation today)

**Comment by RMHogervorst** [comment]
Hi @hrbrmstr I completely forgot about  this issue, but do you have any pointers to how we should fix this multiline issue?

**Comment by RMHogervorst** [comment]
This is only working if you have gpg keys in the local keybase keyring, and I can't seem to get that to work on this computer.
